id: Microsoft Defender - ATP - Indicators SC Test
version: -1
name: Microsoft Defender - ATP - Indicators SC Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 6b20b540-3a19-4552-8faa-caa3a82db627
    type: start
    task:
      id: 6b20b540-3a19-4552-8faa-caa3a82db627
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "20"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: c4d37754-1223-4b3b-887f-d44e5f661d8c
    type: regular
    task:
      id: c4d37754-1223-4b3b-887f-d44e5f661d8c
      version: -1
      name: Get indicators by ID
      description: Gets an indicator by its ID.
      script: '|||microsoft-atp-sc-indicator-get-by-id'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      indicator_id:
        complex:
          root: MicrosoftATP.Indicators
          accessor: id
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1535
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: a96f80b9-1f18-41d9-862e-f65309cd6946
    type: regular
    task:
      id: a96f80b9-1f18-41d9-862e-f65309cd6946
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 117673d2-59e1-4999-8d46-3d079f707bbd
    type: regular
    task:
      id: 117673d2-59e1-4999-8d46-3d079f707bbd
      version: -1
      name: List indicators
      description: Lists all indicators by the ID that the system creates when the
        indicator is ingested.
      script: '|||microsoft-atp-sc-indicator-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 515
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 04712c85-af44-48ed-8185-11ca4f34c976
    type: condition
    task:
      id: 04712c85-af44-48ed-8185-11ca4f34c976
      version: -1
      name: Check number of indicators
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "19"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: greaterThanOrEqual
          left:
            value:
              complex:
                root: MicrosoftATP
                accessor: Indicators
                transformers:
                - operator: count
            iscontext: true
          right:
            value:
              simple: "0"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 23bc2f37-f127-4770-8614-0d069d151f12
    type: title
    task:
      id: 23bc2f37-f127-4770-8614-0d069d151f12
      version: -1
      name: Continue the test
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "26"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1040
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 230baf6c-991a-477b-867b-e4247ed62710
    type: regular
    task:
      id: 230baf6c-991a-477b-867b-e4247ed62710
      version: -1
      name: Update indicators description and severity
      description: Updates the specified indicator.
      script: '|||microsoft-atp-sc-indicator-update'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "28"
    scriptarguments:
      action:
        simple: Allowed
      expiration_time:
        simple: 1 day
      indicator_description:
        simple: newDescription
      indicator_title:
        simple: newTitle
      indicator_type:
        simple: IpAddress
      indicator_value:
        simple: 3.5.6.7
      severity:
        simple: Low
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1710
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "17":
    id: "17"
    taskid: a7b87594-6c16-4a4a-8a75-cb2f34d848b2
    type: title
    task:
      id: a7b87594-6c16-4a4a-8a75-cb2f34d848b2
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2410
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "19":
    id: "19"
    taskid: 203ae72d-b7f0-41d8-83f4-4ed38cc646a7
    type: regular
    task:
      id: 203ae72d-b7f0-41d8-83f4-4ed38cc646a7
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "20":
    id: "20"
    taskid: 79595339-5159-459a-8401-b81e47163b77
    type: title
    task:
      id: 79595339-5159-459a-8401-b81e47163b77
      version: -1
      name: Setup
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "26":
    id: "26"
    taskid: 1d47c61b-db40-48dc-833c-e46e84017da8
    type: regular
    task:
      id: 1d47c61b-db40-48dc-833c-e46e84017da8
      version: -1
      name: microsoft-atp-sc-indicator-create
      description: Creates a new indicator.
      script: '|||microsoft-atp-sc-indicator-create'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "27"
    scriptarguments:
      action:
        simple: Allowed
      expiration_time:
        simple: 1 day
      indicator_description:
        simple: testPlaybook
      indicator_title:
        simple: test-title
      indicator_type:
        simple: IpAddress
      indicator_value:
        simple: 3.5.6.7
      severity:
        simple: Informational
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1185
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "27":
    id: "27"
    taskid: d8ab056d-59e5-4f2e-884b-0afc82876e91
    type: condition
    task:
      id: d8ab056d-59e5-4f2e-884b-0afc82876e91
      version: -1
      name: Check the indicators returned with the High severity
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ${MicrosoftATP.Indicators.severity}
            iscontext: true
          right:
            value:
              simple: Informational
      - - operator: isNotEmpty
          left:
            value:
              simple: ${MicrosoftATP.Indicators.id}
            iscontext: true
      - - operator: isEqualString
          left:
            value:
              simple: ${MicrosoftATP.Indicators.description}
            iscontext: true
          right:
            value:
              simple: testPlaybook
      - - operator: isEqualString
          left:
            value:
              simple: ${MicrosoftATP.Indicators.title}
            iscontext: true
          right:
            value:
              simple: test-title
      - - operator: isEqualString
          left:
            value:
              simple: ${MicrosoftATP.Indicators.action}
            iscontext: true
          right:
            value:
              simple: Allowed
      - - operator: isEqualString
          left:
            value:
              simple: ${MicrosoftATP.Indicators.indicatorType}
            iscontext: true
          right:
            value:
              simple: IpAddress
      - - operator: isEqualString
          left:
            value:
              simple: ${MicrosoftATP.Indicators.indicatorValue}
            iscontext: true
          right:
            value:
              simple: 3.5.6.7
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "28":
    id: "28"
    taskid: 4e7ad983-51e4-453d-8df5-c72f059f06d2
    type: regular
    task:
      id: 4e7ad983-51e4-453d-8df5-c72f059f06d2
      version: -1
      name: Get indicators by ID
      description: Gets an indicator by its ID.
      script: '|||microsoft-atp-sc-indicator-get-by-id'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "29"
    scriptarguments:
      indicator_id:
        complex:
          root: MicrosoftATP.Indicators
          accessor: id
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1885
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "29":
    id: "29"
    taskid: f7f4fb05-b56e-423f-87ce-a1090fcd2880
    type: condition
    task:
      id: f7f4fb05-b56e-423f-87ce-a1090fcd2880
      version: -1
      name: Check the indicators returned with the Low severity and updated fields
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "30"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ${MicrosoftATP.Indicators.severity}
            iscontext: true
          right:
            value:
              simple: Low
      - - operator: isNotEmpty
          left:
            value:
              simple: ${MicrosoftATP.Indicators.id}
            iscontext: true
      - - operator: isEqualString
          left:
            value:
              simple: ${MicrosoftATP.Indicators.description}
            iscontext: true
          right:
            value:
              simple: newDescription
      - - operator: isEqualString
          left:
            value:
              simple: ${MicrosoftATP.Indicators.title}
            iscontext: true
          right:
            value:
              simple: newTitle
      - - operator: isEqualString
          left:
            value:
              simple: ${MicrosoftATP.Indicators.action}
            iscontext: true
          right:
            value:
              simple: Allowed
      - - operator: isEqualString
          left:
            value:
              simple: ${MicrosoftATP.Indicators.indicatorType}
            iscontext: true
          right:
            value:
              simple: IpAddress
      - - operator: isEqualString
          left:
            value:
              simple: ${MicrosoftATP.Indicators.indicatorValue}
            iscontext: true
          right:
            value:
              simple: 3.5.6.7
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2060
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "30":
    id: "30"
    taskid: b947e2c0-f233-4e9f-8960-5f2b513d598e
    type: regular
    task:
      id: b947e2c0-f233-4e9f-8960-5f2b513d598e
      version: -1
      name: Delete Indicator
      description: Deletes the specified indicator.
      script: '|||microsoft-atp-sc-indicator-delete'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      indicator_id:
        simple: ${MicrosoftATP.Indicators.id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2235
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2425,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.0.0
description: Test all the indicators command which use the security center api
